# Site Configuration
baseURL = "https://v1-10.docs.dapr.io"
title = "Dapr Docs"
theme = "docsy"
disableFastRender = true

enableRobotsTXT = true
enableGitInfo = true

# Language Configuration
languageCode = "en-us"

[languages]
  [languages.en]
    title = "Dapr Docs"
    weight = 1
    contentDir = "content/en"
    languageName = "English"
  [languages.zh-hans]
    title = "Dapr 文档库"
    weight = 2
    contentDir = "content/zh-hans"
    languageName = "简体中文"

# Disable categories & tags
disableKinds = ["taxonomy", "term"]

# Google Analytics
[services.googleAnalytics]
id = "G-60C6Q1ETC1"

# Mounts
[module]
  [[module.mounts]]
    source = "content/en"
    target = "content"
    lang = "en"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

  [[module.mounts]]
    source = "../sdkdocs/python/daprdocs/content/en/python-sdk-docs"
    target = "content/developing-applications/sdks/python"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/python/daprdocs/content/en/python-sdk-contributing"
    target = "content/contributing/sdk-contrib/"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/php/daprdocs/content/en/php-sdk-docs"
    target = "content/developing-applications/sdks/php"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/dotnet/daprdocs/content/en/dotnet-sdk-docs"
    target = "content/developing-applications/sdks/dotnet"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/pluggable-components/dotnet/daprdocs/content/en/dotnet-sdk-docs"
    target = "content/developing-applications/develop-components/pluggable-components/pluggable-components-sdks/pluggable-components-dotnet"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/dotnet/daprdocs/content/en/dotnet-sdk-contributing"
    target = "content/contributing/sdk-contrib/"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/go/daprdocs/content/en/go-sdk-docs"
    target = "content/developing-applications/sdks/go"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/go/daprdocs/content/en/go-sdk-contributing"
    target = "content/contributing/sdk-contrib/"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/java/daprdocs/content/en/java-sdk-docs"
    target = "content/developing-applications/sdks/java"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/java/daprdocs/content/en/java-sdk-contributing"
    target = "content/contributing/sdk-contrib/"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/js/daprdocs/content/en/js-sdk-docs"
    target = "content/developing-applications/sdks/js"
    lang = "en"
  [[module.mounts]]
    source = "../sdkdocs/js/daprdocs/content/en/js-sdk-contributing"
    target = "content/contributing/sdk-contrib/"
    lang = "en"

  [[module.mounts]]
    source = "../translations/docs-zh/content/zh-hans"
    target = "content"
    lang = "zh-hans"
  [[module.mounts]]
    source = "../translations/docs-zh/content/contributing"
    target = "content/contributing/docs-contrib/docs-templates"
    lang = "zh-hans"
  [[module.mounts]]
    source = "../translations/docs-zh/content/sdks_python"
    target = "content/developing-applications/sdks/python"
    lang = "zh-hans"
  [[module.mounts]]
    source = "../translations/docs-zh/content/sdks_php"
    target = "content/developing-applications/sdks/php"
    lang = "zh-hans"
  [[module.mounts]]
    source = "../translations/docs-zh/content/sdks_dotnet"
    target = "content/developing-applications/sdks/dotnet"
    lang = "zh-hans"

# Markdown Engine - Allow inline html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Top Nav Bar
[[menu.main]]
    name = "Homepage"
    weight = 40
    url = "https://dapr.io"
[[menu.main]]
    name = "GitHub"
    weight = 50
    url = "https://github.com/dapr"
[[menu.main]]
    name = "Blog"
    weight = 60
    url = "https://blog.dapr.io/posts"
[[menu.main]]
    name = "Discord"
    weight = 70
    url = "https://aka.ms/dapr-discord"
[[menu.main]]
    name = "Community"
    weight = 80
    url = "https://github.com/dapr/community/blob/master/README.md"

[params]
copyright = "The Dapr Authors"
distributed = "Documentation Distributed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)"
trademark = "The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://linuxfoundation.org/trademark-usage/) page."

#privacy_policy = "https://policies.google.com/privacy"

# Algolia
algolia_docsearch = true
offlineSearch = false

# GitHub Information
github_repo = "https://github.com/dapr/docs"
github_project_repo = "https://github.com/dapr/dapr"
github_subdir = "daprdocs"
github_branch = "v1.10"

# Versioning
version_menu = "v1.10"
version = "v1.10"
archived_version = true
url_latest_version = "https://docs.dapr.io"

[[params.versions]]
  version = "v1.12 (preview)"
  url = "https://v1-12.docs.dapr.io"
[[params.versions]]
  version = "v1.11 (latest)"
  url = "#"
[[params.versions]]
  version = "v1.10"
  url = "https://v1-10.docs.dapr.io"
[[params.versions]]
  version = "v1.9"
  url = "https://v1-9.docs.dapr.io"
[[params.versions]]
  version = "v1.8"
  url = "https://v1-8.docs.dapr.io"
[[params.versions]]
  version = "v1.7"
  url = "https://v1-7.docs.dapr.io"
[[params.versions]]
  version = "v1.6"
  url = "https://v1-6.docs.dapr.io"
[[params.versions]]
  version = "v1.5"
  url = "https://v1-5.docs.dapr.io"
[[params.versions]]
  version = "v1.4"
  url = "https://v1-4.docs.dapr.io"
[[params.versions]]
  version = "v1.3"
  url = "https://v1-3.docs.dapr.io"


# UI Customization
[params.ui]
sidebar_menu_compact = true
navbar_logo = true
sidebar_search_disable = true
[params.ui.feedback]
enable = true
yes = '<b>Glad to hear it!</b> Please <a href="https://github.com/dapr/docs/issues/new/choose">tell us how we can improve</a>.'
no = '<b>Sorry to hear that.</b> Please <a href="https://github.com/dapr/docs/issues/new/choose">tell us how we can improve</a>.'

# Links
## End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/daprdev"
	icon = "fab fa-twitter"
  desc = "Follow us on Twitter to get the latest updates!"
[[params.links.user]]
	name = "YouTube"
	url = "https://www.youtube.com/channel/UCtpSQ9BLB_3EXdWAUQYwnRA"
	icon = "fab fa-youtube"
  desc = "Community call recordings and other cool demos"
[[params.links.user]]
	name = "Blog"
	url = "https://blog.dapr.io/posts"
	icon = "fas fa-blog"
  desc = "Community call recordings and other cool demos"
## Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/dapr/"
	icon = "fab fa-github"
  desc = "Development takes place here!"
[[params.links.developer]]
	name = "Discord"
	url = "https://aka.ms/dapr-discord"
	icon = "fab fa-discord"
  desc = "Conversations happen here!"
[[params.links.developer]]
	name = "Zoom"
	url = "https://aka.ms/dapr-community-call"
	icon = "fas fa-video"
  desc = "Meetings happen here!"
